import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/webpage-UI/header/Header'
import Hero from '@/webpage-UI/hero/Hero'
import Features from '@/webpage-UI/features/Features'
import Client from '@/webpage-UI/Client/Client'
import Service from '@/webpage-UI/Service/Service'
import Footer from '@/webpage-UI/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='homepage-maindiv'>
      <Head>
        <title>Keeper | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
           <Header/>
           <Hero/>
           <Features/>
           <Client/>
           <Service/>
           <Footer/>
    </div>
  )
}
